version: '3.6'

services:
  ezproxytools:
    container_name: ezproxytools
    image: ghcr.io/kth-biblioteket/ezproxytools:main
    privileged: true
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - /usr/local/ezproxy:/usr/local/ezproxy
      - /usr/local/ezproxyrepo:/usr/local/ezproxyrepo
      - ./00000020.crt:/app/00000020.crt
      - ./00000020.key:/app/00000020.key
      - ./00000020.ca:/app/00000020.ca